#!/bin/bash

# Removing empty lines
sed -ir '/^\s*$/d' $1

# Remove special character from group name
GROUP_NAME=`grep SubRep $1 | head -1 | cut -d "=" -f2 | sed -r 's/[#$\r ]//g'`

# Remove unwanted lines
sed -i '0,/^\[Bookmark/d' $1
sed -i '0,/SubRep/d' $1
sed -i '0,/ImgNum=/d' $1

while read -r LINE
do
	[[ $LINE =~ ^\[Bookmark ]] && break
	# Extract host info
	HOSTNAME=`echo $LINE | cut -d "=" -f1`
	HOST_IP=`echo $LINE | cut -d% -f2`
	HOST_PORT=`echo $LINE | cut -d% -f3`
	HOST_USERNAME=`echo $LINE | cut -d% -f4`

	# Write host info to file
	echo -e "Host $HOSTNAME\n\tHostName $HOST_IP:$HOST_PORT\n\tUser $HOST_USERNAME" >> $GROUP_NAME
	sed -i '1d' $1
done < "$1"
