#!/bin/bash

SESSIONS_LIST="test"

for PROG in tmux ssh fzf; do
	[ ! `which "$PROG"` ] && echo "Please install "$PROG"!" && exit 1
done

_list(){
   # Chech if list is in connection mode, 1 means connection mode
   if [[ $1 -eq 1 ]]; then
      column -t -s "|" "$SESSIONS_LIST" | fzf -m --reverse | tr '\n' ';'
   else
      column -t -s "|" "$SESSIONS_LIST" | fzf -m --reverse
   fi
}

_connect(){
   IFS=';' read -ra SESSIONS_ARRAY <<< $1
   for SESSION in "${SESSIONS_ARRAY[@]}"; do
      SESSION_NAME=`echo "$SESSION" | awk '{print $1}'`
      SESSION_ADDRESS=`echo "$SESSION" | awk '{print $2"@"$3}'`
      if tmux has-session -t mossh; then
         tmux new-window -t mossh -n "$SESSION_NAME"
      else
         tmux new -s mossh -n "$SESSION_NAME" -d
      fi
      tmux send-keys -t mossh:"$SESSION_NAME" "ssh $SESSION_ADDRESS" C-m
      [ `tmux ls | grep mossh | grep -c attached` -eq 0 ] && tmux a -t mossh
   done
}

while getopts "lch?" opt 
do
   case "$opt" in
      l)
         _list 0
         exit 0
				;;
			c) 
         SESSIONS=`_list 1`
         #echo $SESSIONS
         [[ -z "$SESSIONS" ]] && exit 0
         _connect "$SESSIONS"
        ;;
      h\?) # display _help
         _help
         exit 0;;
   esac
done

shift $((OPTIND-1))
[ "${1:-}" = "--" ] && shift
